steps:
## Shinkwrap
- name: 'gcr.io/$PROJECT_ID/faas-cli:0.12.14'
  args: ['faas-cli', 'template', 'store', 'pull', 'node12']
  
- name: 'gcr.io/$PROJECT_ID/faas-cli:0.12.14'
  args: ['faas-cli', 'build', '--shrinkwrap']
  
## Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/timezone-shift:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/timezone-shift:latest', '-f' ,'./build/timezone-shift/Dockerfile', './build/timezone-shift/']

## Deploy to "Cloud Run"
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'timezone-shift', '--image', 'gcr.io/$PROJECT_ID/timezone-shift:$REVISION_ID', '--region', 'europe-west1']

images: 
- 'gcr.io/$PROJECT_ID/timezone-shift'
